name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup openGL
      run: sudo apt-get install mesa-common-dev freeglut3-dev
    - name: cmake
      run: cmake ./
    - name: make
      run: make
